### ISSUE TITLE
git submodule update --init fails

### ISSUE THREAD

**Issue by Claudius42** [idbrii/daveconfig#3]
Hi,

I tried to get your setup running on Ubuntu 14.04 64-bit but did not succeed.

**That's what I did:**
- clone master branch of daveconfig
- executed `makelinks_unix.sh` (making sure that all links are successfully created)
- `$> git submodule update --init ` --> lead to following output:

```
.... many other moduls
Submodul 'multi/vim/bundle/xmledit' (git@github.com:idbrii/xmledit.git) für Pfad 'multi/vim/bundle/xmledit' in die Konfiguration eingetragen.
Submodul 'multi/vim/bundle/xolox-misc' (https://github.com/xolox/vim-misc.git) für Pfad 'multi/vim/bundle/xolox-misc' in die Konfiguration eingetragen.
Submodul 'unix/terminal/bashmarks' (git@github.com:idbrii/bashmarks.git) für Pfad 'unix/terminal/bashmarks' in die Konfiguration eingetragen.
Klone nach 'multi/git/submanage' ...
The authenticity of host 'github.com (192.30.253.113)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? y
Please type 'yes' or 'no': yes
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Cloning from 'git@github.com:idbrii/git-submanage.git' to path Submodul 'multi/git/submanage' failed
```

**Do you have any idea what is going wrong or what I missed to do?**

**Many thanks in advance**

**Comment by idbrii** [comment]
Can you see https://github.com/idbrii/git-submanage

The repo isn't private, so there isn't a good reason why it wouldn't work.

I have had similar errors that seem to be connection issues with github and retrying works fine. (Haven't investigated to see why.)

You could try again, you could try to specifically init that submodule,. or you could try cloning that repo and ensure that works for you.
